### ISSUE TITLE
Sandbox: test-cloud submit ssl error

### ISSUE THREAD

**Issue by sapieneptus** [calabash/install#25] opened 2015-12-09 02:14 UTC
```
### Negotiating upload ###
/Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/xamarin-test-cloud-1.1.2/lib/xamarin-test-cloud/cli.rb:720:in `http_post'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/xamarin-test-cloud-1.1.2/lib/xamarin-test-cloud/cli.rb:563:in `gather_files_and_paths_to_upload'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/xamarin-test-cloud-1.1.2/lib/xamarin-test-cloud/cli.rb:431:in `submit_test_job'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/xamarin-test-cloud-1.1.2/lib/xamarin-test-cloud/cli.rb:280:in `submit'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/X/.calabash/sandbox/Gems/ruby/2.1.0/gems/xamarin-test-cloud-1.1.2/bin/test-cloud:7:in `<top (required)>'
	from /Users/X/.calabash/sandbox/Gems/bin/test-cloud:16:in `load'
	from /Users/X/.calabash/sandbox/Gems/bin/test-cloud:16:in `<main>'
```

@jmoody have you seen this one?
CC: @kymphillpotts

**Comment by jmoody** [comment] 2016-01-08 10:21
No.  

I am going to close this because we are not using RestClient any more - as of xamarin-test-cloud 2.0.0.pre2.

I am working on reproducing another SSL bug (I mentioned to you yesterday).

**Closed by jmoody** 2016-01-08 10:21 UTC
